name: Bun NestJS Template
description: A modern NestJS template using Bun.js runtime and Biome.js for linting/formatting
tags:
  - nestjs
  - bun
  - typescript
  - biome
  - backend
  - api
  - template


